### ISSUE TITLE
TypeError: "$css" already loading

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#100]
```
error [TypeError: "$css" already loading] TypeError: "$css" already loading
```

Happens if application has ```*.less``` and ```*.css``` dependencies 

Exact configuration that causes it is not clear.

Full output:
```text
error [TypeError: "$css" already loading] TypeError: "$css" already loading
    at ...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1547:17
    at init (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:396:5)
    at new Promise (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:384:53)
    at loadModule (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1351:12)
    at ...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:2124:11
    at tryCatchReject (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1091:30)
    at runContinuation1 (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1061:4)
    at Fulfilled.when (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:877:4)
    at Pending.run (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:771:13)
    at runQueue (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:182:18)
    at Scheduler._drain (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:157:3)
    at Scheduler.drain (...\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:133:9)
ERROR: Cannot read property 'order' of undefined TypeError: Cannot read property 'order' of undefined
    at visit (...\node_modules\steal-tools\lib\graph\order.js:7:12)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
Potentially unhandled rejection [7] TypeError: Cannot read property 'order' of undefined
    at visit (...\node_modules\steal-tools\lib\graph\order.js:7:12)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
    at ...\node_modules\steal-tools\lib\graph\order.js:11:5
    at Array.forEach (native)
    at visit (...\node_modules\steal-tools\lib\graph\order.js:10:22)
```

**Comment by matthewp** [comment]
@mehiel Were you ever able to figure anything out? If there is a reproducible way to make the bug happen we'll be able to fix it.

**Comment by matthewp** [comment]
Going to merge the test: https://github.com/stealjs/steal-tools/pull/225

Please reopen if you have an example of this failing.
