### ISSUE TITLE
0.6.0 (multi)-build error on windows

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal-tools#162]
0.6.0 on windows

```
info: OPENING: web/web
error: Cannot read property 'graph' of undefined TypeError: Cannot read property 'graph' of undefined
    at D:\Code\front-app\node_modules\steal-tools-new\lib\graph\make_graph_with_bundles.js:42:25
    at tryCatchReject (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1091:30)
    at runContinuation1 (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:1061:4)
    at Fulfilled.when (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:877:4)
    at Pending.run (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:771:13)
    at runQueue (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:182:18)
    at Scheduler._drain (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:157:3)
    at Scheduler.drain (D:\Code\front-app\node_modules\steal-tools\node_modules\steal\node_modules\systemjs\node_modules\es6-module-loader\dist\es6-module-loader.js:133:9)
    at process._tickDomainCallback (node.js:459:13)
Fatal error: window is not defined
Process finished with exit code 3
```

grunt task confg
```javascript
options: {
            system: {
                config: 'file:///' + dirname.replace(/\\/g, '/').replace(/^[A-Z]:/, '') + "/stealconfig.web.js",
                main: "web/web",
                paths: {
                    '@dev': 'bower_components/steal/dev.js'
                },
                bundlesPath: 'dist/web/bundles',
                bundle: [
                    'components/promo-page/promo-page',
                    'components/content-view/content-view'
                ]
            },
            buildOptions: {
                bundleSteal: true
            }
        }
```

had to add ```@dev': 'bower_components/steal/dev.js'``` because without it it can not find '@dev' module (error about `file URL`)

**Comment by matthewp** [comment]
We have been tracking the `file:` problem on windows... not sure if there is a bug yet for that. But it's being worked on currently, once it's fixed maybe you can retry?

**Comment by whitecolor** [comment]
well of course I will retry. You shure that it is because of `file;`?

**Comment by matthewp** [comment]
Working on the bug as we speak!

**Comment by matthewp** [comment]
So we are fixing the bug in steal currently: https://github.com/bitovi/steal/issues/328

You won't have to do `file:` or the replace any more. Instead of 

```js
config: 'file:///' + dirname.replace(/\\/g, '/').replace(/^[A-Z]:/, '') + "/stealconfig.web.js",
```

you can do:

```js
config: require("path").join(__dirname, "stealconfig.web.js"),
```

this is the "correct" way to path on windows.

This isn't guaranteed to fix every Windows issue but I promise you that making Steal and Steal-tools work flawlessly on Windows is a top priority right now and we hope to have things much better by 0.7.0.

**Comment by whitecolor** [comment]
> We're going to also add CI for Windows through http://www.appveyor.com/ so all of our tests will run on Windows.

Well I think for now it would be enough just before release of changes run couple of test builds on windows. It would identify majority of problems as a node environment usually works well on all platfroms.

**Comment by matthewp** [comment]
This should be fixed now, the correct way to pass a config (or any path on Windows) is:

```js
config: require("path").join(__dirname, "stealconfig.web.js")
```
