### ISSUE TITLE
Live-reload not working with Vue.js

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal-tools#464]
I made an example of how to use Steal with Vue.js.  Running `steal-tools live-reload` produces an error.  It's caused when steal tries to process the package called `envify`, which is found in vue's package.json:

https://github.com/vuejs/vue/blob/dev/package.json#L45

For some reason, that package comes through wrapped in an array and breaks [at this line in the npm-utils](https://github.com/stealjs/steal/blob/master/ext/npm-utils.js#L147)

Here's the error I'm getting.
```
Bitovis-MacBook-Pro:steal-vuejs marshall$ steal-tools live-reload
OPENING: /Users/marshall/Sites/steal-vuejs/package.json!npm
steal - error loading @config. [TypeError: Error loading "package.json!npm" at file:/Users/marshall/Sites/steal-vuejs/package.json
moduleName.split is not a function]
Potentially unhandled rejection [4] TypeError: Error loading "package.json!npm" at file:/Users/marshall/Sites/steal-vuejs/package.json
moduleName.split is not a function
    at Object.utils.moduleName.parse (file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm-utils.js:149:33)
    at convertBrowserProperty (file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm-convert.js:249:43)
    at Object.convertBrowser [as browser] (file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm-convert.js:239:3)
    at Array.<anonymous> (file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm.js:68:23)
    at Object.utils.forEach (file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm-utils.js:56:7)
    at file:/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal/ext/npm.js:56:9
    at tryCatchReject (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at ContinuationTask.run (/Users/marshall/.nvm/versions/node/v5.10.1/lib/node_modules/steal-tools/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1040:24)
```

**Comment by matthewp** [comment]
Which version of steal-tools?

**Comment by matthewp** [comment]
I ran steal-tools from the node_modules folder and didn't get that problem:

<img width="682" alt="screen shot 2016-05-18 at 8 13 37 am" src="https://cloud.githubusercontent.com/assets/361671/15358077/7c7a3c02-1cd0-11e6-83d9-328808281d9c.png">

See what your `steal-tools --version` is.

**Comment by marshallswain** [comment]
Bitovis-MacBook-Pro:Sites marshall$ steal-tools --version
0.15.7

**Comment by matthewp** [comment]
Can you upgrade to latest and let me know?

**Comment by marshallswain** [comment]
Yep.  It's fixed.
