### ISSUE TITLE
Source Map is not generated for configDependencies

### ISSUE THREAD

**Issue by obaidott** [stealjs/steal-tools#509]
When build a custom build via stealTools, the source map for fixtures (listed as configDependencies) is not generated. 

```
stealTools.build({
  config: `${__dirname}/package.json!npm`,
  main: 'public/index',
  configDependencies: [],
  bundlesPath: 'public/dist'
}, {
  sourceMaps: true,
  sourceMapsContent: true,
  quiet: false,
  debug: true
}).then(reportCoverage);
```

I am using remap-istanbul to parse the coverage file (json).

Error Log:
```
Error: Could not find source map for: "/Users/ob/Development/bitovi/Trouper/public/fixtures/config.js"
    at /Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:213:11
    at Array.forEach (native)
    at /Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:192:22
    at Array.forEach (native)
    at remap (/Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:191:12)
    at testee.test.then (/Users/ob/Development/bitovi/Trouper/coverage.js:68:28)
    at _fulfilled (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:796:13)
    at /Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:604:44
Error: Could not find source map for: "/Users/ob/Development/bitovi/Trouper/public/fixtures/deparam.js"
    at /Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:213:11
    at Array.forEach (native)
    at /Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:192:22
    at Array.forEach (native)
    at remap (/Users/ob/Development/bitovi/Trouper/node_modules/remap-istanbul/lib/remap.js:191:12)
    at testee.test.then (/Users/ob/Development/bitovi/Trouper/coverage.js:68:28)
    at _fulfilled (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:796:13)
    at /Users/ob/Development/bitovi/Trouper/node_modules/q/q.js:604:44
```

This project is using es6.

**Comment by matthewp** [comment]
Looking into this now.

**Comment by matthewp** [comment]
@obaidott I added https://github.com/stealjs/steal-tools/pull/510 which is a test that has a configDependency and verifies it is included within the sourceMap. It is using sourceMaps: true and sourceMapsContent: true like you are using.  Is there something different about your usage?

**Comment by pYr0x** [comment]
@obaidott can you give us more information? does the build still not work for you?
otherwise, can i close the issue?

**Comment by matthewp** [comment]
Closing for now, will reopen if we can get more info.
