### ISSUE TITLE
Failed build should result in exit code 1

### ISSUE THREAD

**Issue by alexisabril** [stealjs/steal-tools#611]
Using a build script as below, fails with exit code `0` currently. The failure is due to a misconfiguration on our part, however exit code `1` is beneficial(specifically for CI environments).

Build script:
```
const steal = require('steal-tools');

steal.build({
	config: __dirname + '/package.json!npm'
}, {
	minify: true
});
```

Output:
```
OPENING: /myProject/package.json!npm
steal - error loading @config. Error: Error loading "package.json!npm" at file:/myProject/package.json
Did not find ./node_modules/waypoints/package.json
    at FetchTask.next (file:/myProject/node_modules/steal/ext/npm-crawl.js:532:11)
    at file:/myProject/node_modules/steal/ext/npm-crawl.js:556:33
    at tryCatchReject (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:821:13)
    at Scheduler._drain (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:97:19)
    at Scheduler.drain (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Potentially unhandled rejection [7] Error: Error loading "package.json!npm" at file:/myProject/package.json
Did not find ./node_modules/waypoints/package.json
    at FetchTask.next (file:/myProject/node_modules/steal/ext/npm-crawl.js:532:11)
    at file:/myProject/node_modules/steal/ext/npm-crawl.js:556:33
    at tryCatchReject (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1183:30)
    at runContinuation1 (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:1142:4)
    at Fulfilled.when (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:930:4)
    at Pending.run (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:821:13)
    at Scheduler._drain (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:97:19)
    at Scheduler.drain (/myProject/node_modules/steal-es6-module-loader/dist/es6-module-loader.src.js:62:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
bash$ echo $?
bash$ 0
```

**Comment by matthewp** [comment]
Looks to me like this is a case of Promises swallowing an error. If you were to do:

```js
const steal = require('steal-tools');

steal.build({
	config: __dirname + '/package.json!npm'
}, {
	minify: true
})
.catch(function(err){
  setTimeout(function(){
    throw err;
  });
});
```

Do you get exit of 1?

**Comment by alexisabril** [comment]
Good call. That fixes the issue. Is this something we should add into `build` or should the pattern to be adding a `catch` with a re-throw?

**Comment by matthewp** [comment]
Yeah, I think that's a good idea.

**Comment by alexisabril** [comment]
Which is a good idea? 😄 

I could be swayed either way. Since we're using `build` in a script and it returns a promise, perhaps the responsibility does lie with the consumer to produce the correct error codes. This is in the instance someone would want to do some other step if a steal build fails.

**Comment by matthewp** [comment]
Yeah, it's definitely the responsibility of the Promise consumer to handle errors.

I thought you meant that maybe the DoneJS generator should make sure that the build.js it generators does the rethrow trick.

**Comment by matthewp** [comment]
Going to close this as I don't think there's anything to change in steal-tools

**Comment by justinbmeyer** [comment]
Just checking .... do our command line tools exit with a failure though?

**Comment by matthewp** [comment]
Yep, they do: https://github.com/stealjs/steal-tools/blob/master/lib/cli/cmd_build.js#L32
