### ISSUE TITLE
Cannot create slim build when using npm plugin

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal-tools#730]
```
Cannot read property 'type' of undefined
    at isStatement (/Users/mmujica/Projects/slim-css/node_modules/escodegen/escodegen.js:80:59)
    at generateInternal (/Users/mmujica/Projects/slim-css/node_modules/escodegen/escodegen.js:2489:13)
    at Object.generate (/Users/mmujica/Projects/slim-css/node_modules/escodegen/escodegen.js:2558:18)
    at generate (/Users/mmujica/Projects/slim-css/node_modules/transpile/lib/generate.js:20:25)
    at Object.to (/Users/mmujica/Projects/slim-css/node_modules/transpile/main.js:74:10)
    at /Users/mmujica/Projects/slim-css/node_modules/steal-tools/lib/graph/transpile.js:110:22
    at module.exports (/Users/mmujica/Projects/slim-css/node_modules/steal-tools/lib/node/transform_active_source.js:18:47)
    at transpileNode (/Users/mmujica/Projects/slim-css/node_modules/steal-tools/lib/graph/transpile.js:43:3)
    at /Users/mmujica/Projects/slim-css/node_modules/steal-tools/lib/graph/transpile.js:127:4
    at Array.forEach (native)
```

**Comment by matthewp** [comment]
@m-mujica please add an estimate to this, thanks.
