### ISSUE TITLE
Cannot redefine property: default

### ISSUE THREAD

**Issue by jeroencornelissen** [stealjs/steal-tools#817]
Ever since updating to `steal-tools` > `1.8.0` we have this error. 
When navigating to #!Planner the planner bundle is loaded but throws an error:

```
Error loading \"planner-app@1.0.0#planner/planner\" at https://sub.domain.com/modules/Planner/planner-app/dist/src/planner/planner.js
Cannot redefine property: default",
  "stack": "TypeError: Error loading \"planner-app@1.0.0#planner/planner\" at https://sub.domain.com/modules/Planner/planner-app/dist/src/planner/planner.js
  Cannot redefine property: default
      at Function.defineProperty (<anonymous>)
      at o (https://sub.domain.com/modules/Planner/planner-app/dist/bundles/planner-app/planner/planner.js:2:32462)
      at Function.eval (https://sub.domain.com/modules/Planner/planner-app/dist/bundles/planner-app/planner/planner.js:2:33526)
      at execute (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:48967)
      at h (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:39506)
      at h (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:39468)
      at c (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:38170)
      at Object.execute (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:41893)
      at h (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:18913)
      at m (https://sub.domain.com/modules/Planner/planner-app/dist/steal.production.rev-97190c3cf9.js:11:19283)"
}
```

Steal tries to load `https://sub.domain.com/modules/Planner/planner-app/dist/src/planner/planner.js` but that file doesn't exist.
`https://sub.domain.com/modules/Planner/planner-app/dist/bundles/planner-app/planner/planner.js ` exists and gets loaded.

Other bundles, in the same app, don't have this problem.

If we build with `1.7.2` everything works.

**Comment by matthewp** [comment]
Sorry about this, will take a look.  Will likely move over to steal-tools when we narrow it down.

**Comment by matthewp** [comment]
Oh, this is in steal-tools. Sorry, it's early. 😂

**Comment by matthewp** [comment]
Is the problem that it is loading the wrong file, or the error message you see there?  I'm not sure I can help on that error message without more info. Is it related to the build somehow?

**Comment by jeroencornelissen** [comment]
Yes, somehow related to the build. Ever since steal-tools 1.8.0.
It tries to load `dist/src/planner/planner.js ` but `dist/src` doesn't exist.

**Comment by jeroencornelissen** [comment]
Narrowed it down to a helper file that had an `export default` and an `export const function`.
I've created an other file with the `export const function` and imported it. That solved the issue.
So maybe some strange behavior from our side...
