### ISSUE TITLE
Support @steal in slim build

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal-tools#849]
@imaustink commented on [Fri Sep 22 2017](https://github.com/stealjs/stealjs/issues/77)

```
Potentially unhandled rejection [1] Error: Cannot create slim build. "@steal" module is not supported
    at isAtSteal (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:32:9)
    at Array.forEach (<anonymous>)
    at /Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:21:21
    at Array.forEach (<anonymous>)
    at module.exports (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/slim/checks/steal.js:10:14)
    at checkSupport (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/stream/check_slim_support.js:20:2)
    at DestroyableTransform._transform (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/steal-tools/lib/stream/check_slim_support.js:10:15)
    at DestroyableTransform.Transform._read (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/austinkurpuis/bitovi/bitcentive/public/node_modules/readable-stream/lib/_stream_writable.js:406:64)
```

This is preventing Bitcentive from taking advantage of the slim build, as many of its dependencies, for example,  `steal-socket.io`, use `@steal`.

---

@imaustink commented on [Fri Sep 22 2017](https://github.com/stealjs/stealjs/issues/77#issuecomment-331488969)

cc @matthewp @m-mujica

**Comment by matthewp** [comment]
Simple implementation would be:

```js
steal = {};
steal.loader = require("@loader");
steal.done = Promise.resolve();
```

As a start at least, that accounts for most usage.
